name = "gleam_bitwise"
version = "1.1.0"
licences = ["Apache-2.0"]
description = "Bitwise operations on integers"

repository = { type = "github", user = "gleam-lang", repo = "bitwise" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.18"

[dev-dependencies]
gleeunit = "~> 0.1"
